//>>built
define("dojox/grid/enhanced/plugins/Rearrange","dojo/_base/kernel,dojo/_base/lang,dojo/_base/declare,dojo/_base/array,dojo/_base/connect,../../EnhancedGrid,../_Plugin,./_RowMapLayer".split(","),function(p,r,s,k,m,t,v,w){p=s("dojox.grid.enhanced.plugins.Rearrange",v,{name:"rearrange",constructor:function(b,a){this.grid=b;this.setArgs(a);var f=new w(b);dojox.grid.enhanced.plugins.wrap(b,"_storeLayerFetch",f)},setArgs:function(b){this.args=r.mixin(this.args||{},b||{});this.args.setIdentifierForNewItem=
this.args.setIdentifierForNewItem||function(a){return a}},destroy:function(){this.inherited(arguments);this.grid.unwrap("rowmap")},onSetStore:function(){this.grid.layer("rowmap").clearMapping()},_hasIdentity:function(b){var a=this.grid,f=a.store,e=a.layout.cells;return f.getFeatures()["dojo.data.api.Identity"]&&k.some(b,function(c){return f.getIdentityAttributes(a._by_idx[c.r].item)==e[c.c].field})?!0:!1},moveColumns:function(b,a){var f=this.grid,e=f.layout,c=e.cells,h,d,g=0,j=!0;h={};var i={};b.sort(function(a,
c){return a-c});for(d=0;d<b.length;++d)h[b[d]]=d,b[d]<a&&++g;var l=0,n=0,k=Math.max(b[b.length-1],a);k==c.length&&--k;var q=Math.min(b[0],a);for(d=q;d<=k;++d){var o=h[d];0<=o?i[d]=a-g+o:d<a?(i[d]=q+l,++l):d>=a&&(i[d]=a+b.length-g+n,++n)}g=0;a==c.length&&(--a,j=!1);f._notRefreshSelection=!0;for(d=0;d<b.length;++d){h=b[d];h<a&&(h-=g);++g;if(h!=a)e.moveColumn(c[h].view.idx,c[a].view.idx,h,a,j),c=e.cells;a<=h&&++a}delete f._notRefreshSelection;m.publish("dojox/grid/rearrange/move/"+f.id,["col",i,b])},
moveRows:function(b,a){var f=this.grid,e={},c=[],h=[],d=b.length,g,j,i;for(g=0;g<d;++g){h=b[g];if(h>=a)break;c.push(h)}h=b.slice(g);if(d=c.length){i={};k.forEach(c,function(a){i[a]=!0});e[c[0]]=a-d;for(j=0,g=c[j]+1,c=g-1;g<a;++g)i[g]?(++j,e[g]=a-d+j):(e[g]=c,++c)}c=h;if(d=c.length){i={};k.forEach(c,function(a){i[a]=!0});e[c[d-1]]=a+d-1;for(j=d-1,g=c[j]-1,c=g+1;g>=a;--g)i[g]?(--j,e[g]=a+j):(e[g]=c,--c)}var l=r.clone(e);f.layer("rowmap").setMapping(e);f.forEachLayer(function(a){return"rowmap"!=a.name()?
(a.invalidate(),!0):!1},!1);f.selection.selected=[];f._noInternalMapping=!0;f._refresh();setTimeout(function(){m.publish("dojox/grid/rearrange/move/"+f.id,["row",l,b]);f._noInternalMapping=!1},0)},moveCells:function(b,a){var f=this.grid,e=f.store;if(e.getFeatures()["dojo.data.api.Write"]&&!(b.min.row==a.min.row&&b.min.col==a.min.col)){var c=f.layout.cells,h,d,g,j,i=[],l=[];for(h=b.min.row,g=a.min.row;h<=b.max.row;++h,++g)for(d=b.min.col,j=a.min.col;d<=b.max.col;++d,++j){for(;c[d]&&c[d].hidden;)++d;
for(;c[j]&&c[j].hidden;)++j;i.push({r:h,c:d});l.push({r:g,c:j,v:c[d].get(h,f._by_idx[h].item)})}this._hasIdentity(i.concat(l))?console.warn("Can not write to identity!"):(k.forEach(i,function(a){e.setValue(f._by_idx[a.r].item,c[a.c].field,"")}),k.forEach(l,function(a){e.setValue(f._by_idx[a.r].item,c[a.c].field,a.v)}),e.save({onComplete:function(){m.publish("dojox/grid/rearrange/move/"+f.id,["cell",{from:b,to:a}])}}))}},copyCells:function(b,a){var f=this.grid,e=f.store;if(e.getFeatures()["dojo.data.api.Write"]&&
!(b.min.row==a.min.row&&b.min.col==a.min.col)){var c=f.layout.cells,h,d,g,j,i=[];for(h=b.min.row,g=a.min.row;h<=b.max.row;++h,++g)for(d=b.min.col,j=a.min.col;d<=b.max.col;++d,++j){for(;c[d]&&c[d].hidden;)++d;for(;c[j]&&c[j].hidden;)++j;i.push({r:g,c:j,v:c[d].get(h,f._by_idx[h].item)})}this._hasIdentity(i)?console.warn("Can not write to identity!"):(k.forEach(i,function(a){e.setValue(f._by_idx[a.r].item,c[a.c].field,a.v)}),e.save({onComplete:function(){setTimeout(function(){m.publish("dojox/grid/rearrange/copy/"+
f.id,["cell",{from:b,to:a}])},0)}}))}},changeCells:function(b,a,f){var e=this.grid,c=e.store;if(c.getFeatures()["dojo.data.api.Write"]){var h=e.layout.cells,d=b.layout.cells,g,j,i,l,n=[];for(g=a.min.row,i=f.min.row;g<=a.max.row;++g,++i)for(j=a.min.col,l=f.min.col;j<=a.max.col;++j,++l){for(;d[j]&&d[j].hidden;)++j;for(;h[l]&&h[l].hidden;)++l;n.push({r:i,c:l,v:d[j].get(g,b._by_idx[g].item)})}this._hasIdentity(n)?console.warn("Can not write to identity!"):(k.forEach(n,function(a){c.setValue(e._by_idx[a.r].item,
h[a.c].field,a.v)}),c.save({onComplete:function(){m.publish("dojox/grid/rearrange/change/"+e.id,["cell",f])}}))}},clearCells:function(b){var a=this.grid,f=a.store;if(f.getFeatures()["dojo.data.api.Write"]){var e=a.layout.cells,c,h,d=[];for(c=b.min.row;c<=b.max.row;++c)for(h=b.min.col;h<=b.max.col;++h){for(;e[h]&&e[h].hidden;)++h;d.push({r:c,c:h})}this._hasIdentity(d)?console.warn("Can not write to identity!"):(k.forEach(d,function(c){f.setValue(a._by_idx[c.r].item,e[c.c].field,"")}),f.save({onComplete:function(){m.publish("dojox/grid/rearrange/change/"+
a.id,["cell",b])}}))}},insertRows:function(b,a,f){try{var e=this.grid,c=e.store,h=e.rowCount,d={},g=0,j=[],i,l=0>f,n=this,p=a.length;if(l)f=0;else for(i=f;i<e.rowCount;++i)d[i]=i+p;if(c.getFeatures()["dojo.data.api.Write"]){if(b){var q=b.store,o,u;if(l)u=k.filter(k.map(e.layout.cells,function(a){return a.field}),function(a){return a});else{for(i=0;!o;++i)o=e._by_idx[i];u=c.getAttributes(o.item)}var s=[];k.forEach(a,function(a,e){var i={},l=b._by_idx[a];if(l){k.forEach(u,function(a){i[a]=q.getValue(l.item,
a)});i=n.args.setIdentifierForNewItem(i,c,h+g)||i;try{c.newItem(i),j.push(f+e),d[h+g]=f+e,++g}catch(m){console.log("insertRows newItem:",m,i)}}else s.push(a)})}else if(a.length&&r.isObject(a[0]))k.forEach(a,function(a,b){var e=n.args.setIdentifierForNewItem(a,c,h+g)||a;try{c.newItem(e),j.push(f+b),d[h+g]=f+b,++g}catch(i){console.log("insertRows newItem:",i,e)}});else return;e.layer("rowmap").setMapping(d);c.save({onComplete:function(){e._refresh();setTimeout(function(){m.publish("dojox/grid/rearrange/insert/"+
e.id,["row",j])},0)}})}}catch(t){console.log("insertRows:",t)}},removeRows:function(b){var a=this.grid,f=a.store;try{k.forEach(k.map(b,function(c){return a._by_idx[c]}),function(a){a&&f.deleteItem(a.item)}),f.save({onComplete:function(){m.publish("dojox/grid/rearrange/remove/"+a.id,["row",b])}})}catch(e){console.log("removeRows:",e)}},_getPageInfo:function(){var b=this.grid.scroller,a=b.page,f=b.page,e=b.firstVisibleRow,c=b.lastVisibleRow,h=b.rowsPerPage,d,g,j,i=[];k.forEach(b.pageNodes[0],function(b,
k){b&&(j=!1,d=k*h,g=(k+1)*h-1,e>=d&&e<=g&&(a=k,j=!0),c>=d&&c<=g&&(f=k,j=!0),!j&&(d>c||g<e)&&i.push(k))});return{topPage:a,bottomPage:f,invalidPages:i}}});t.registerPlugin(p);return p});